[phases.setup]
nixPkgs = ["python311", "postgresql"]

[phases.install]
cmds = ["cd trucking-planner/backend && pip install -r requirements.txt"]

[start]
cmd = "cd trucking-planner/backend && python manage.py migrate && gunicorn --bind 0.0.0.0:$PORT --workers 2 core.wsgi:application"
